dist: bionic
services: docker
language: bash

env:
  global:
    - PACKAGE_NAME=mcl_3dl_msgs
  matrix:
    - ROS_DISTRO_TARGET=kinetic
    - ROS_DISTRO_TARGET=melodic
branches:
  only:
    - master

before_install:
  - curl -sL https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/install.sh | sh -s
script:
  - cp ~/.local/bin/gh-pr-comment .travis/
  - docker build
    -t mcl-3dl-msgs
    -f .travis/Dockerfile
    --pull=true ${TRAVIS_BUILD_DIR}
    --build-arg ROS_DISTRO=${ROS_DISTRO_TARGET}
    || (gh-pr-comment "[#${TRAVIS_BUILD_NUMBER}] FAILED on ${ROS_DISTRO_TARGET}" "docker build failed"; false)
  - docker run --rm -it
    -e TRAVIS_BUILD_NUMBER
    $(sh <(curl -s https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/env.sh))
    mcl-3dl-msgs /catkin_ws/src/${PACKAGE_NAME}/.travis/test.sh
